name: Publish prelysia

on:
  push:
    tags:
      - 'prelysia-v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/prelysia
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bun publish --access public
        env:
          BUN_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
